name: DinoCash

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    services:
        db_dino:
          image: mariadb:latest
          ports:
            - 3306:3306
          env:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dinocash
            MYSQL_USER: dinocash
            MYSQL_PASSWORD: dinocash
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'

      - name: Install Composer Dependencies
        run: |
          cd volumes/dinocash
          composer install --no-scripts --no-interaction --no-progress --prefer-dist
          
      - name: Copy .env
        run: |
          cd volumes/dinocash
          php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Application Key
        run: |
          cd volumes/dinocash
          php artisan key:generate

      - name: Directory Permissions
        run: |
          cd volumes/dinocash
          chmod -R 777 storage bootstrap/cache

      - name: Install Pest
        run: |
          cd volumes/dinocash
          composer require pestphp/pest --dev

      - name: Execute Pest tests
        run: |
          cd volumes/dinocash
          php artisan migrate
          ./vendor/bin/pest
