name: DinoCash CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      db_dino:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          TZ: America/Sao_Paulo
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dinocash
          MYSQL_USER: dinocash
          MYSQL_PASSWORD: dinocash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"

      - name: Install Composer Dependencies
        run: |
          cd volumes/dinocash
          composer install --no-scripts --no-interaction --no-progress --prefer-dist

      - name: Copy .env
        run: |
          cd volumes/dinocash
          php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Application Key
        run: |
          cd volumes/dinocash
          php artisan key:generate

      - name: Directory Permissions
        run: |
          cd volumes/dinocash
          chmod -R 777 storage bootstrap/cache

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install npm dependencies
        run: |
          cd volumes/dinocash
          npm install

      - name: Install Pest
        run: |
          cd volumes/dinocash
          composer require pestphp/pest --dev

      - name: Change DB_HOST in .env
        run: sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' volumes/dinocash/.env

      - name: NPM Run build
        run: |
          cd volumes/dinocash
          npm run build

      - name: Execute Pest tests
        run: |
          cd volumes/dinocash
          php artisan migrate
          ./vendor/bin/pest
  laravel-deploy:
    runs-on: ubuntu-latest
    
    needs: laravel-tests

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: SSH into Server
        run: ssh root@limbotecnologia.com.br

      - name: CD into Project
        run: cd projects/dinocash

      - name: Switch to Main Branch and Pull
        run: |
          git switch main
          git pull

      - name: Run Artisan Migrate and NPM Build
        run: |
          docker-compose exec php_dino php artisan migrate
          npm run build
